config/routes.rb
Rails.application.routes.draw do
  resources :messages
  devise_for :users
  resources :inboxes
  root 'static_pages#landing_page'
  get 'pricing', to: 'static_pages#pricing'
  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'
end

app/models/inbox.rb
class Inbox < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy

  MIN_NAME = 6
  MAX_NAME = 100

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { in: MIN_NAME..MAX_NAME }
end

app/controllers/inboxes_controller.rb
class InboxesController < ApplicationController
  before_action :set_inbox, only: %i[show edit update destroy]

  # GET /inboxes or /inboxes.json
  def index
    @inboxes = Inbox.all
  end

  # GET /inboxes/1 or /inboxes/1.json
  def show; end

  # GET /inboxes/new
  def new
    @inbox = Inbox.new
  end

  # GET /inboxes/1/edit
  def edit; end

  # POST /inboxes or /inboxes.json
  def create
    # due to session addition we cannot create a new inbox without being
    # logged in
    @inbox = current_user.inboxes.new(inbox_params)

    respond_to do |format|
      if @inbox.save
        format.html { redirect_to inbox_url(@inbox), notice: 'Inbox was successfully created.' }
        format.json { render :show, status: :created, location: @inbox }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inboxes/1 or /inboxes/1.json
  def update
    respond_to do |format|
      if @inbox.update(inbox_params)
        format.html { redirect_to inbox_url(@inbox), notice: 'Inbox was successfully updated.' }
        format.json { render :show, status: :ok, location: @inbox }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inboxes/1 or /inboxes/1.json
  def destroy
    @inbox.destroy

    respond_to do |format|
      format.html { redirect_to inboxes_url, notice: 'Inbox was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_inbox
    @inbox = Inbox.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def inbox_params
    params.require(:inbox).permit(:name)
  end
end

app/helpers/inboxes_helper.rb
module InboxesHelper
end

app/views/inboxes/_form.html.erb
<%= form_with(model: inbox) do |form| %>
  <% if inbox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inbox.errors.count, "error") %> prohibited this inbox from being saved:</h2>

      <ul>
        <% inbox.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inboxes/_inbox.html.erb
<div id="<%= dom_id inbox %>" class="scaffold_record">
  <p>
    <strong>Name:</strong>
    <%= inbox.name %>
  </p>

  <%= inbox.user.email %>
</div>

app/views/inboxes/edit.html.erb
<h1>Editing inbox</h1>

<%= render "form", inbox: @inbox %>

<br>

<div>
  <%= link_to "Show this inbox", @inbox %> |
  <%= link_to "Back to inboxes", inboxes_path %>
</div>

app/views/inboxes/index.html.erb
<h1>Inboxes</h1>

<div id="inboxes">
  <% @inboxes.each do |inbox| %>
    <%= render inbox %>
    <p>
      <%= link_to "Show this inbox", inbox %>
    </p>
  <% end %>
</div>

<%= link_to "New inbox", new_inbox_path %>

app/views/inboxes/new.html.erb
<h1>New inbox</h1>

<%= render "form", inbox: @inbox %>

<br>

<div>
  <%= link_to "Back to inboxes", inboxes_path %>
</div>

app/views/inboxes/show.html.erb
<%= render @inbox %>

<div>
  <%= link_to "Edit this inbox", edit_inbox_path(@inbox) %> |
  <%= link_to "Back to inboxes", inboxes_path %>

  <%= button_to "Destroy this inbox", @inbox, method: :delete %>
</div>